### PR TITLE
fix UI elements for login dialog

### PR DESCRIPTION
**Pull request by mohitsuman**
Signed-off-by: Mohit Suman <mohit.skn@gmail.com>

### CODE REVIEW

**Comment by fbricon** [comment]
@mohitsuman most of those changes have been included already, or are no longer relevant. The only remaining difference is whether we still want to switch from `filled` inputs:
Screenshot 2022-05-18 at 12 19 00

to `outlined`
Screenshot 2022-05-18 at 12 18 24

Which actually doesn't look that good because of the misaligned header (similar to https://github.com/docker/extensions-sdk/issues/175#issue-1235625867)

@mohitsuman so, WDYT?

**Comment by dgolovin** [comment]
This is known issue [#175](https://github.com/docker/extensions-sdk/issues/175)

**Comment by fbricon** [comment]
The alignment fix is available in @docker/docker-mui-theme 0.0.7:
Screenshot 2022-06-01 at 14 11 47

@mohitsuman is this something you want us to apply now?

**Comment by mohitsuman** [comment]
@fbricon yes let's get this fix in the extension. I think the change looks good and better than the grey background and overlapping text.

**Comment by fbricon** [comment]
Fixed in https://github.com/redhat-developer/openshift-dd-ext/commit/282cb7bb2c771f5932902b26261d4a2e10272188
See

**Pull request closed without merging**
